---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: SecureYellow
# description will be included in the image's metadata
description: This is my personal OS image based on Arch and bootc

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/bootcrew/arch-bootc
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: pacman
    install:
      packages:
        - base
        
      # Archinstall pipewire
        - pipewire
        - pipewire-alsa
        - pipewire-jack
        - pipewire-pulse
        - gst-plugin-pipewire
        - libpulse
        - wireplumber
      
      # Archinstall bluetooth
        - bluez
        - bluez-utils

      # Archinstall firewall
        - firewalld
      
      # Archinstall power management
        - power-profiles-daemon

      # Archinstall printer
        - cups
        - system-config-printer
        - cups-pk-helper
      
      # Archinstall Desktop
        - nano
        - vim
        - openssh
        - htop
        - wget
        - smartmontools
        - xdg-utils
      
      # Archinstall fonts
        - noto-fonts
        - noto-fonts-emoji
        - noto-fonts-cjk
        - ttf-liberation
        - ttf-dejavu

      # Archinstall KDE Plasma
      #  - plasma-meta


  - type: signing # this sets up the proper policy & signing files for signed images to work fully
