---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: secureyellow
# description will be included in the image's metadata
description: This is my personal OS image based on Arch and bootc

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/bootcrew/arch-bootc
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: pacman
    install:
      remove:
        - glibc
        - linux
        - man
        - man-db

  - type: pacman
    install:
      packages:
        - base
      # Archinstall pipewire
        - pipewire
        - pipewire-alsa
        - pipewire-jack
        - pipewire-pulse
        - gst-plugin-pipewire
        - libpulse
        - wireplumber
      
      # Archinstall bluetooth
        - bluez
        - bluez-utils

      # Archinstall firewall
        - firewalld
      
      # Archinstall power management
        - power-profiles-daemon

      # Archinstall printer
        - cups
        - system-config-printer
        - cups-pk-helper
      
      # Archinstall Desktop
        - nano
        - vim
        - openssh
        - htop
        - wget
        - smartmontools
        - xdg-utils
      
      # Archinstall fonts
        - noto-fonts
        - noto-fonts-emoji
        - noto-fonts-cjk
        - ttf-liberation
        - ttf-dejavu

        - # Base packages
        - linux-hardened
        - glibc-locales
        - nftables
        - util-linux
        - cryptsetup
        - apparmor
        - audit
        - fakeroot
        - debugedit
        - man-db
        - man-pages
        - just
        - whois
        - git
        - mokutil
        - fsverity-utils
        - sbctl
        - sbsigntools
        - gnulib-l10n
        - efitools
        - jq
        - rsync
        - rclone
        - bash-completion
        - dosfstools
        - tpm2-tools
        - amd-ucode
        - linux-firmware

        - # network
        - networkmanager
        - network-manager-applet

        - # HP
        - hplip

        - # desktop
        - iwd
        - wireless_tools
        - bolt
        - desktop-file-utils
        - pax-utils
        - pgpdump
        - qemu-guest-agent
        - wireless-regdb
        - xdg-desktop-portal
        - tesseract-data-deu
        - tesseract-data-eng

        - # plasma
        - plasma-meta
        - ark
        - sddm
        - bluedevil
        - breeze-gtk
        - kde-gtk-config
        - kdeplasma-addons
        - kgamma
        - kinfocenter
        - kscreen
        - ksshaskpass
        - kwallet-pam
        - kwrited
        - ocean-sound-theme
        - plasma-desktop
        - plasma-disks
        - plasma-nm
        - plasma-pa
        - plasma-systemmonitor
        - plasma-thunderbolt
        - plasma-welcome
        - plasma-workspace-wallpapers
        - powerdevil
        - sddm-kcm
        - xdg-desktop-portal-kde
        - flatpak-kcm
        - konsole
        - dolphin
        - spectacle
        - skanpage
        - kate
        - filelight
        - 
        - # Additional packages
        - firefox
        - spice-vdagent
        - flatpak
        - thunderbird
        - thunderbird-i18n-de
        - thunderbird-i18n-en-us
        - torbrowser-launcher
        - sydbox
        - pandora_box
        - kernel-hardening-checker

        - # Virtualization
        - libvirt
        - dnsmasq
        - qemu-desktop
        - virt-firmware
        - edk2-ovmf
        - virt-manager
        - virt-viewer

        # Containers
        - passt
        - podman

        # Devel
        - base-devel

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
