name: bluebuild
on:
  pull_request:
  workflow_dispatch: # allow manually triggering builds
  # schedule:
  # - cron:
  #     "00 06 * * *" # build at 06:00 UTC every day
      # (20 minutes after last ublue images start building)
  # push:
  #   paths-ignore: # don't rebuild if only documentation has changed
  #     - "**.md"
concurrency:
  # only run one build at a time
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
jobs:
  bluebuild:
    name: Build Custom Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false # stop GH from cancelling all matrix builds if one fails
      matrix:
        recipe:
          # !! Add your recipes here
          - recipe.yml
    steps:
      # the build is fully handled by the reusable github action
      - name: Build Custom Image
        uses: blue-build/github-action@v1.11
        with:
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
          push: false
          # enabled by default, disable if your image is small and you want faster builds
          maximize_build_space: true
      - name: List images
        run: |
          echo "Podman: $(podman images)"
          echo "Docker: $(docker images)"
          echo "Buildah: $(buildah images)"
      - name: Seal image
        uses: PhysicsIsAwesome/bootc-seal-action@test
        with:
            input-image: secureyellow
            output-image: secureyellow-sealed
            signing-key: ${{ secrets.DB_KEY }}
            signing-cert: ${{ secrets.DB_CRT }}
            cmdline: "rw rootflags=subvol=root rd.luks.name=7fa68618-91b8-4cf6-8a30-6c662331b0c7=luks-7fa68618-91b8-4cf6-8a30-6c662331b0c7 root=/dev/mapper/luks-7fa68618-91b8-4cf6-8a30-6c662331b0c7"