name: seal
on:
  pull_request:
  workflow_dispatch: # allow manually triggering builds
  workflow_run:
    workflows: [bluebuild]
    types: completed
  # schedule:
  # - cron:
  #     "00 06 * * *" # build at 06:00 UTC every day
      # (20 minutes after last ublue images start building)
  # push:
  #   paths-ignore: # don't rebuild if only documentation has changed
  #     - "**.md"
concurrency:
  # only run one build at a time
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
jobs:
  seal:
    name: Seal Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false # stop GH from cancelling all matrix builds if one fails
    steps:
      - name: Seal image
        uses: PhysicsIsAwesome/bootc-seal-action@test
        with:
            input-image: ghcr.io/physicsisawesome/secureyellow:br-basic-arch-setup-latest-20260607
            output-image: secureyellow-sealed
            signing-key: "${{ secrets.DB_KEY }}"
            signing-cert: "${{ secrets.DB_CRT }}"
            cmdline: "rw rootflags=subvol=root rd.luks.name=7fa68618-91b8-4cf6-8a30-6c662331b0c7=luks-7fa68618-91b8-4cf6-8a30-6c662331b0c7 root=/dev/mapper/luks-7fa68618-91b8-4cf6-8a30-6c662331b0c7"